#!/usr/bin/python3

import fnmatch
import os
import re

def findfiles(which, where='.'):
    '''Returns list of filenames from `where` path matched by 'which'
       shell pattern. Matching is case-insensitive.'''
    rule = re.compile(fnmatch.translate(which), re.IGNORECASE)
    return [name for name in os.listdir(where) if rule.match(name)]


if __name__ == '__main__':
    files = findfiles("*.mp3")
    curdir = os.path.basename(os.getcwd())
    listname = curdir + ".m3u"
    mlist = open(listname, "w")
    for f in files:
        mlist.write(f + "\n")
    mlist.close()

        

